Repository practical-python-org/ZorakBot, pull requests merged in 2023-11, with the labels that each got.

#255 fix: Increase translation threshold
  setup.py
  src/zorak/cogs/general/general_trans.py
Labels: bug, enhancement

#265 Added logging to the on_verified button push for a new user joining.
  src/zorak/cogs/admin/verification_on_verified.py
  src/zorak/cogs/logging/logging_name_changes.py
Labels: BUG, EASY

#266 fix: Verification Logging fix
  src/zorak/cogs/admin/verification_on_verified.py
  src/zorak/cogs/logging/logging_name_changes.py
Labels: BUG, EASY

#267 fix: Oopsie
  src/zorak/cogs/admin/verification_on_verified.py
Labels: BUG, EASY

#283 minor: dad joke command
  src/zorak/cogs/general/general_dadjoke.py
Labels: FEATURE

#274 Feature/anti spam protection
  src/zorak/cogs/admin/_admin_automod_spam_messages.py
  src/zorak/cogs/admin/admin_automod_spam_messages.py
  src/zorak/utilities/cog_helpers/_embeds.py
Labels: FEATURE

#284 minor: anti-spam, dad jokes and Dev times
  Dockerfile
  README.md
  docker-compose.yaml
  requirements.txt
  setup.py
  src/zorak/cogs/admin/_admin_automod_spam_messages.py
  src/zorak/cogs/admin/admin_automod_spam_messages.py
  src/zorak/cogs/admin/admin_startup.py
  src/zorak/cogs/general/general_dadjoke.py
  src/zorak/cogs/general/general_devtimes.py
  src/zorak/utilities/cog_helpers/_embeds.py
  src/zorak/utilities/core/mongo.py
Labels: FEATURE

#286 fix/auto-spam-quarantine
  src/zorak/cogs/admin/admin_automod_spam_messages.py
Labels: BUG, EASY

#287 fix: auto-spam fix for verification removal
  src/zorak/cogs/admin/admin_automod_spam_messages.py
Labels: BUG, EASY

#296 minor: Addition of the trivia cog
  src/zorak/cogs/general/general_trivia.py
Labels: FEATURE, MODERATE, ZORAKATHON

#306 fix/on message edit fix
  src/zorak/cogs/logging/logging_message_edit.py
  src/zorak/utilities/cog_helpers/_embeds.py
Labels: BUG
